# Generated by Django 4.0 on 2021-12-14 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0003_flight_price_per_seat_infant_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="flight",
            old_name="price_per_seat_infant",
            new_name="price_per_seat_underage",
        ),
    ]
