# Generated by Django 4.0 on 2021-12-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0004_rename_price_per_seat_infant_flight_price_per_seat_underage"),
    ]

    operations = [
        migrations.AddField(
            model_name="seat",
            name="is_bought",
            field=models.BooleanField(default=False, verbose_name="Куплено"),
        ),
    ]
