# Generated by Django 4.0 on 2021-12-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0006_order_citizenship_country_order_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Актуален'),
        ),
    ]
