# Generated by Django 4.0 on 2021-12-14 15:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0007_order_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата рождения'),
        ),
    ]
